import { Outfit } from "next/font/google"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const font = Outfit({
  subsets: [ "latin"],
  weight: [ "400", "700" ]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
